---
version: 1
build:
  bash_commands: "mvn clean install -DskipTests"
deploy:
  bash_commands: "echo $NEXUS_REPO_ID ; mvn clean deploy -DskipTests -DaltDeploymentRepository=mks-nexus::default::https://nexus.mekomsolutions.net/repository/maven-snapshots"
